kind: pipeline
type: docker
name: default
steps:
- name: build
  image: maven:3.8.5-openjdk-8
  volumns:
    - name: maven-build
      path: /root/.m2
    - name: jar-build
      path: /opt/app
  commands: 
    - chmod +x /opt/app/*.sh
    - if [ -d spring-drone-test ]; then
    - cd spring-drone-test
    - $MAVEN_HOME/bin/mvn -v
    - $MAVEN_HOME/bin/mvn clean package -DskipTests=true
    - cp target/*.jar /opt/app
    - cp Dockerfile /opt/app
    - cd /opt/app
    - docker build -t spring-drone-test:latest
    - docker rm -f testDrone
    - docker run --name testDrone -d -p 8088:8088 spring-drone-test:latest
    - fi
  when:
    event: push
volumns:
  - name: maven-build
    host:
      path: /opt/drone/m2-cache
  - name: jar-build
    host:
      path: /opt/app
