kind: pipeline
type: docker
name: default
steps:
- name: build
  image: docker:23
  commands: 
  - |
    if [-d spring-drone-test]; then
    cd spring-drone-test
    ./.drone.yml
    fi
  when:
    event: push
- name: greeting
  image: alpine
  commands: 
  - echo hello
  - echo world
