kind: pipeline
type: docker
name: default

steps:
- name: publish      # 推送镜像到harbor仓库
  pull: if-not-exists
  image: plugins/docker
  settings: 
    dockerfile: ./Dockerfile
    tags: latest
    insecure: true  # 是否不安全。即是https还是http，这里为http
    repo: 192.168.153.132:100/library/drone-demo
    registry: 192.168.153.132:100
    username:   # 从drone仓库配置中秘密空间读取用户名
      from_secret: HARBOR_USERNAME
    password:   # 从drone仓库配置中秘密空间读取密码
      from_secret: HARBOR_PASSWORD

- name: deploy       # 使用ssh访问主机，拉取镜像并运行部署
  pull: if-not-exists
  image: appleboy/drone-ssh
  settings:
    host: http://192.168.153.132  # 需要部署的主机
    port: 22               # 主机ssh端口
    username: root         # 主机登录用户名
    password:
      from_secret: ssh_pwd # 从drone仓库配置中秘密空间读取密码
    script:
      - echo ======暂停并删除旧容器======
      - docker stop drone-demo-1 && docker rm drone-ci-demo-1
      - docker stop drone-demo-2 && docker rm drone-ci-demo-2
      - echo ======删除旧镜像===========
      - docker rmi 192.168.153.132:100/library/drone-ci-demo:latest
      - echo ======从harbor拉取最新镜像==
      - docker pull 192.168.153.132:100/library/drone-ci-demo:latest
      - echo ======运行镜像=============
      - docker run --name drone-demo-1 -p 8001:80 -d 192.168.153.132:100/library/drone-demo:latest
      - docker run --name drone-demo-2 -p 8002:80 -d 192.168.153.132:100/library/drone-demo:latest
      - echo ======部署成功=============
