kind: pipeline
type: docker
name: default

steps:
  - name: greeting
    image: alpine
    commands:
      - echo Hello Drone
  - name: fr
    image: alpine
    commands:
      - echo so hard
    when:
      event: push
      branch: master
